default:
  base_input_dir: data

  parser_config:
    output_format: markdown
    keep_pageheader_in_output : False
    keep_pagefooter_in_output : False

  chunker_config:
    chunker_method : MarkdownHeaderTextSplitter
    chunk_size: 512
    chunk_overlap: 128
    chunker_params:
      headers_to_split_on: 
        - ('#', 'Header 1')
        - ("##", "Header 2")
        - ("###", "Header 3")
        - ("####", "Header 4")
      strip_headers: False

  
  vectorstore_config:
    vectorstore_path: storage/vectorstore_512_128
    vectorstore_class : Chroma
    embedding_class : GoogleGenerativeAIEmbeddings
    use_parent_doc_retriever: False

    vectorstore_params:
      collection_metadata:
        hnsw:space: cosine

    embedding_params:
      model : gemini-embedding-001

    retriever_params:
      search_type: similarity
      search_kwargs:
        k : 15


  ensemble_config:
    top_n : 10
    vectorstore_weight: 0.5
    lexicalstore_weight: 0.5

  rerank_config:
    rerank_class : CohereRerank
    rerank_params:
      model: rerank-v3.5
      top_n : 10


  lexicalstore_config:
    lexicalstore_path: storage/lexicalstore_512_128_uni.pkl
    lexicalstore_class : BM25Retriever
    lexicalstore_params: 
      k : 15

      
  generator_config:
    generator_class : ChatOpenAI
    generator_params:
      model : gpt-4.1-mini
      temperature: 0.0
      top_p : 0.0